# Generated by Django 4.2.5 on 2023-09-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_avatar_avatar_id_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desciption',
            new_name='description',
        ),
    ]
