# Generated by Django 4.2.5 on 2023-09-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_desciption_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='desciption',
            new_name='description',
        ),
    ]
