# Generated by Django 4.2.6 on 2023-10-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_remove_task_due_date_remove_task_room_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="frequency",
            field=models.FloatField(),
        ),
    ]
