# Generated by Django 4.2.6 on 2023-10-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_task_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
