# Generated by Django 4.2.6 on 2023-10-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_user_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="source",
            field=models.CharField(max_length=200),
        ),
    ]
